name: Deno lint fmt test

on: [push, pull_request]

jobs:
  deno_lint_fmt:
    name: Lint Format and Test all deno files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Run Deno fmt check
        run: deno fmt --check

      - name: Run Deno lint
        run: deno lint

      # - name: Setup Hardhat
      #   working-directory: ./packages/contracts
      #   run: deno i

      # - name: Compile Hardhat
      #   working-directory: ./packages/contracts
      #   run: deno task compile

      # - name: Run Contracts tests
      #   working-directory: ./packages/contracts
      #   run: |
      #     nohup deno task localnode >/dev/null 2>&1 &
      #     sleep 5 &
      #     deno test --allow-net
